name: Flatter

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  flatter:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:25.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Flatter
        uses: andyholmes/flatter@v1
        with:
          files: |
            src/org.freedesktop.Sdk.Extension.podman/org.freedesktop.Sdk.Extension.podman.yml
